Update colorbar tick names in sunpath gallery example
pvlib/pvlib-python pull request #2097
Opened 2024-06-20 17:09 UTC by AdamRJensen

- [x] Closes #1998
 - [x] I am familiar with the [contributing guidelines](https://pvlib-python.readthedocs.io/en/latest/contributing.html)
 - [ ] Pull request is nearly complete and ready for detailed review.
 - [x] Maintainer: Appropriate GitHub Labels (including `remote-data`) and Milestone are assigned to the Pull Request and linked Issue.

2024-06-20 17:33 UTC, AdamRJensen commented
@echedey-ls, @IoannisSifnaios, @RDaxini

Hi GSoC students
This PR is rather simple, but could be a good exercise for you to review

2024-06-20 17:41 UTC, echedey-ls commented
Great @AdamRJensen ! I will review in depth later.

Handy links:
- This PR example: https://pvlib-python--2097.org.readthedocs.build/en/2097/gallery/solar-position/plot_sunpath_diagrams.html#sphx-glr-gallery-solar-position-plot-sunpath-diagrams-py
- Stable example: https://pvlib-python.readthedocs.io/en/stable/gallery/solar-position/plot_sunpath_diagrams.html#sphx-glr-gallery-solar-position-plot-sunpath-diagrams-py

2024-06-20 18:40 UTC, echedey-ls commented
Let's add @PhilBrk8 to the whatsnew file:

```* :ghuser:`PhilBrk8` ```

2024-06-21 08:19 UTC, IoannisSifnaios reviewed
Looks great! Just a few ideas from my side

2024-06-21 08:19 UTC, IoannisSifnaios commented on docs/examples/solar-position/plot_sunpath_diagrams.py
>      label = date.strftime('%Y-%m-%d')
I suggest you also do that in the previous figure

2024-06-21 08:19 UTC, IoannisSifnaios commented on docs/examples/solar-position/plot_sunpath_diagrams.py
>                      s=2, label=None, c=solpos.index.dayofyear)
If you apply this, do it also in the figure below

2024-06-21 08:22 UTC, IoannisSifnaios commented on docs/examples/solar-position/plot_sunpath_diagrams.py
>      label = date.strftime('%Y-%m-%d')
I find it very annoying that I can't comment on lines that have not been changed... I guess this is a GitHub thing though! Anyway, maybe also modify the text to say that "....  The `solid` colored lines show the...."

2024-06-21 09:19 UTC, RDaxini reviewed
Thanks for the notification @AdamRJensen .
Mostly looks fine to me but two things I noticed;

1. Could we switch to 24hr format for the times in the docs? Not sure if there is a preference for pvlib docs but I think it would be a more standard way to write the times and also be consistent with the times 06--19 on the figure already.
2.  Is it possible them to align the times on the figure so that they are all above the orange 2019-06-21 line, as 19 is?

2024-06-21 09:20 UTC, RDaxini requested changes
Thanks for the notification @AdamRJensen .
Mostly looks fine to me but two things I noticed;

1. Could we switch to 24hr format for the times in the docs? As opposed to writing AM/PM. Not sure if there is a preference for pvlib docs but I think it would be a more standard way to write the times, easily understood, and also be consistent with the times 06--19 on the figure already.
2. Is it possible them to align the times on the figure so that they are all above the orange 2019-06-21 line, as 19 is?

2024-06-21 15:19 UTC, AdamRJensen commented
@kandersolar I've addressed @RDaxini's review as well so this PR should be ready to merge. Might as well get it out of the way with the release of 0.11.0.

2024-06-21 16:00 UTC, kandersolar approved these changes

2024-06-21 16:00 UTC, merged

2024-06-24 16:17 UTC, PhilBrk8 commented
> Let's add @PhilBrk8 to the whatsnew file:
> 
> `` * :ghuser:`PhilBrk8` ``
> 
> EDIT: LGTM the code from a quick glance

The Whatsnew-file is what exactly?
I get notified of every change?
 - Would be down for it.
 ...even if life gets in the way a lot, I still plan on contributing more to Open Source and picked out this library to do so -

2024-06-24 16:42 UTC, echedey-ls commented
Hey @PhilBrk8 !

> The Whatsnew-file is what exactly?

It is the changelog, a set of files that summarize the changes made to each one of the past releases and the next one. They are the source file(s) to build the following page: https://pvlib-python.readthedocs.io/en/stable/whatsnew.html

> I get notified of every change?

You won't. We mention you in the [contributors section](https://pvlib-python.readthedocs.io/en/stable/whatsnew.html#contributors). It's a way of encouraging and giving credit to contributors. You can find yourself listed on the previous link. Even though your PR wasn't merged, the original idea is still yours.

Feel free to contribute whenever you can and want, you will be welcomed here!